// This file is auto-generated by Lovable, extended for multi-platform / Vercel deployment.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import type { OAuthProvider } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

function isLovablePreview(): boolean {
  if (typeof window === "undefined") return false;
  const host = window.location.hostname;
  const PREVIEW_ZONES = [
    "lovableproject.com",
    "lovableproject-dev.com",
    "lovable.app",
    "gpt-eng.com",
    "gptengineer.run",
  ];
  return PREVIEW_ZONES.some((z) => host === z || host.endsWith("." + z));
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      const redirectUri =
        opts?.redirect_uri ||
        (typeof window !== "undefined" ? window.location.origin : undefined);

      // On Lovable preview surfaces, use the Lovable OAuth broker
      if (isLovablePreview()) {
        try {
          const result = await lovableAuth.signInWithOAuth(provider, {
            ...opts,
            redirect_uri: redirectUri,
            extraParams: {
              ...opts?.extraParams,
            },
          });

          if (result.redirected) {
            return result;
          }

          if (result.error) {
            return result;
          }

          if (result.tokens) {
            try {
              await supabase.auth.setSession(result.tokens);
            } catch (e) {
              return { error: e instanceof Error ? e : new Error(String(e)) };
            }
            return result;
          }
        } catch (e) {
          console.warn("[LovableAuth] Broker error, falling back to Supabase OAuth:", e);
        }
      }

      // On Vercel, localhost, or custom domains, authenticate directly with Supabase OAuth
      try {
        const queryParams: Record<string, string> = {
          ...opts?.extraParams,
        };
        const googleClientId =
          import.meta.env['VITE_GOOGLE_CLIENT_ID'] ||
          process.env['VITE_GOOGLE_CLIENT_ID'] ||
          '392855055307-dhehfd8fepvl20k85v57q785p8rv47h1.apps.googleusercontent.com';
        if (googleClientId) {
          queryParams['client_id'] = googleClientId;
        }

        const { data, error } = await supabase.auth.signInWithOAuth({
          provider: provider as "google",
          options: {
            redirectTo: redirectUri,
            queryParams,
          },
        });
        if (error) {
          return { error };
        }
        if (data?.url) {
          if (typeof window !== "undefined") {
            window.location.href = data.url;
          }
          return { error: null, redirected: true };
        }
        return { error: null, redirected: false };
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
    },
  },
};

